# v2 syntax
version: '2'

# Named volumes
volumes:

  # MySQL Data
  laravel-mysql-data:
    driver: local

services:

  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - laravel-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=task_db
      - MYSQL_USER=arquivei
      - MYSQL_PASSWORD=1234

  # PHP (with Nginx)
  # you can change from nginx to apache, just change session 'image'
  app:
    image: ambientum/php:7.2-nginx
    container_name: laravel-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql